build:
  cuda_version: 12.1.1
  system_packages:
    - "ffmpeg"
  python_packages:
    - "accelerate==1.0.0"
    - "transformers==4.45.2"
    - "librosa==0.10.2.post1"
    - "soundfile==0.12.1"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.27.1"
